const GENERATION = {
  FETCH: "GENERATION_FETCH",
  FETCH_ERROR: "GENERATION_FETCH_ERROR",
  FETCH_SUCCESS: "GENERATION_FETCH_SUCCESS",
};

const PERSONA = {
  FETCH: "PERSONA_FETCH",
  FETCH_ERROR: "PERSONA_FETCH_ERROR",
  FETCH_SUCCESS: "PERSONA_FETCH_SUCCESS",
};

const ACCOUNT = {
  FETCH: "ACCOUNT_FETCH",
  FETCH_ERROR: "ACCOUNT_FETCH_ERROR",
  FETCH_SUCCESS: "ACCOUNT_FETCH_SUCCESS",
  FETCH_LOGOUT_SUCCESS: "ACCOUNT_FETCH_LOGOUT_SUCCESS",
  FETCH_AUTHENTICATED_SUCCESS: "ACCOUNT_FETCH_AUTHENTICATED_SUCCESS",
};

const ACCOUNT_PERSONAS = {
  FETCH: "ACCOUNT_PERSONAS_FETCH",
  FETCH_ERROR: "ACCOUNT_PERSONAS_FETCH_ERROR",
  FETCH_SUCCESS: "ACCOUNT_PERSONAS_FETCH_SUCCESS",
};

const ACCOUNT_INFO = {
  FETCH: "ACCOUNT_INFO_FETCH",
  FETCH_ERROR: "ACCOUNT_INFO_FETCH_ERROR",
  FETCH_SUCCESS: "ACCOUNT_INFO_FETCH_SUCCESS",
};
export { GENERATION, PERSONA, ACCOUNT, ACCOUNT_PERSONAS, ACCOUNT_INFO };
